#+Title: Principle of Programming Languages
# Subtitle: Computer Science 3mi3, McMaster University
#+Author: Mark Armstrong
#+Description: README and the inlined homepage

* Maintainer notes                              :noexport:

** Subtrees

The git subtrees
for [[https://github.com/fniessen/org-html-themes][org-html-themes]]
and [[https://github.com/hakimel/reveal.js][reveal.js]]
were added via the following shell commands.
#+begin_src sh :results none
git subtree add --prefix org-html-themes https://github.com/fniessen/org-html-themes master --squash
#+end_src
#+begin_src sh :results none
git subtree add --prefix notes/reveal.js https://github.com/hakimel/reveal.js master --squash
#+end_src

They can be updated via these commands.
#+begin_src sh :results none
git subtree pull --prefix org-html-themes https://github.com/fniessen/org-html-themes master --squash
#+end_src
#+begin_src sh :results none
git subtree pull --prefix notes/reveal.js https://github.com/hakimel/reveal.js master --squash
#+end_src


* Introduction
:PROPERTIES:
:CUSTOM_ID: org-anchor-Introduction^1
:END:

Repository of course notes and publically available assignment/test documents
# for the course “CS3mi3: Principles of Programming Languages”
# at McMaster University.
for a Principles of Programming Languages course;
most recently, in 2020, specifically Computer Science 3mi3 at McMaster University.

The remainder of this README is an inlined copy of
the some of the main contents of the course homepage, better viewed at
[[https://armkeh.github.io/principles-of-programming-languages/]]

* Macros                                        :noexport:

We need to include these macro definitions here for the included bits.
#+include: "./index.org::*Macros" :only-contents t

* Course outline

#+include: "./index.org::*Course outline" :only-contents t

* Notes

#+include: "./index.org::*Notes" :only-contents t

* Literate programs

#+include: "./index.org::*Literate programs" :only-contents t

* Homework

#+include: "./index.org::*Homework" :only-contents t

* Assignments

#+include: "./index.org::*Assignments" :only-contents t

* Appendices

#+include: "./index.org::*Appendices" :only-contents t

* Language information

#+include: "./index.org::*Language information" :only-contents t

* ~gitignore~                                   :noexport:

#+begin_src text :tangle ./.gitignore
# This file is tangled from README.org and
# should not be modified directly.

# scratch files
*scratch.*

# Local backups
*.*~
*.*#

# LaTeX generation artifacts
*.aux
*.log
*_minted*
#+end_src

