# Define the argument for openjdk version
ARG OPENJDK_TAG=8u232

FROM clojure:openjdk-8
    
# Set the name of the maintainers
MAINTAINER Habib Ghaffari Hadigheh, Mark Armstrong <ghaffh1@mcmaster.ca, armstmp@mcmaster.ca>

# Set the working directory
WORKDIR /opt/h8
