version: '2'
services:
  service:
    build: .
    image: 3mi3_h10_docker_image
    volumes:
      - .:/opt/h10
    container_name: 3mi3_h10_container
    command: bash -c
      "echo 'Scala testing' ;
       echo '----------------------------------------------------------------------' ;
       timeout 2m amm h10t.sc ;
       printf '\\n\\n\\n' ;
       echo 'Scala testing (alternate)' ;
       echo '----------------------------------------------------------------------' ;
       timeout 2m amm h10ta.sc ;
       printf '\\n\\n\\n' ;
       echo 'Ruby testing' ;
       echo '----------------------------------------------------------------------' ;
       timeout 2m ruby h10t.rb ;
       echo '----------------------------------------------------------------------' ;
       printf '\\n\\n\\n' ;
       echo 'Clojure testing' ;
       echo '----------------------------------------------------------------------' ;
       cat h10t.clj | timeout 2m lein repl ;
       echo '----------------------------------------------------------------------'"
