#+Title: Computer Science 3MI3 – 2020 assignment 3
#+Subtitle: A representation of Dijkstra's guarded command language
#+Author: Mark Armstrong
#+Date: December 2, 2020
#+Description: Implementing various operational semantics of 
#+Description: various versions of the guarded command language.
#+Options: num:nil
#+SETUPFILE: ../org-html-themes/setup/theme-readtheorg-local.setup

* LaTeX settings                                :noexport:

#+LaTeX_header: \usepackage{amsthm}
#+LaTeX_header: \theoremstyle{definition}
#+LaTeX_header: \newtheorem{definition}{Definition}[section]

#+LaTeX_header: \usepackage{unicode-math}
#+LaTeX_header: \usepackage{unicode}

* Introduction
:PROPERTIES:
:CUSTOM_ID: Introduction
:END:

This assignment tasks you with representing
Dijkstra's “guarded command language” in
Ruby and Clojure,
and defining various semantics for it.

* Updates and file history
:PROPERTIES:
:CUSTOM_ID: Updates-and-file-history
:END:

** December 16th

Some corrections have been made to the assignment description,
and unfortunately to some of the test cases.

In decreasing order of severity:
- The test cases in the Ruby portions for the “oscillating” statement/program
  did not correctly add the initial assignment to the variable
  to the program, and so will fail (the ~do~ will never run,
  because ~:x~ is assigned ~0~ by default which is outside the
  range for the oscillation, but ~:x~ can never become ~2~ or ~8~.)
- The Ruby part 4 test which checks the scoping of the program
  “~global; local x in x := x should be well scoped.~”
  previously had a typo in the test itself,
  with the variable on the right of the assignment being a ~y~.
  This has been corrected.
- Previously, it was stated that the ~eval~ method in part 4
  was to operate on ~GCStmt~'s. However, it should instead
  operate on ~GCProgram~'s, that is, statements with global variable lists.
- Previously, ~GCAnd~ and ~GCOr~ were incorrectly stated
  to operate on ~GCExpr~'s. They are now correctly stated to operate
  on ~GCTest~'s.
- The broken link to the Ruby testing at the top of that section
  has been replaced with the links to the two Ruby test files.

** December 11th
:PROPERTIES:
:CUSTOM_ID: December-11th
:END:

- The testing and Docker setup has been added.
- The method from part 2 has been renamed to ~stackEval~,
  instead of ~stack_eval~.
- Mark amounts were added to each part.
- Some minor clarifying statements have been added to parts 2, 3 and 4.
  They are prepended by “(Added December 11th.)” 

** December 1st
:PROPERTIES:
:CUSTOM_ID: December-1st
:END:

- Initial version posted.

* Boilerplate
:PROPERTIES:
:CUSTOM_ID: Boilerplate
:END:

** Documentation
:PROPERTIES:
:CUSTOM_ID: Submission-procedures
:END:

#+INCLUDE: "./../boilerplate.org::*Assignment documentation" :only-contents t

** Submission procedures
:PROPERTIES:
:CUSTOM_ID: Submission-procedures
:END:

#+INCLUDE: "./../boilerplate.org::*Assignment submission" :only-contents t

** Proper conduct for coursework
:PROPERTIES:
:CUSTOM_ID: Proper-conduct-for-coursework
:END:

#+INCLUDE: "./../boilerplate.org::*Assignment conduct" :only-contents t

* Part 0 – The guarded command language, /GCL/
:PROPERTIES:
:CUSTOM_ID: Part-0-–-The-guarded-command-language,-/GCL/
:END:

This assignment involves representing a simple
kind of /guarded command language/, which we call /GCL/,
and a small extension to it which we call /GCLe/,
which adds a notion of scope.

** /GCL/
:PROPERTIES:
:CUSTOM_ID: /GCL/
:END:

The syntax of /GCL/ is given as
#+begin_src text
⟨expr⟩ ∷= constant_integer | variable
        | ⟨expr⟩ ('+' | '*' | '-' | '÷') ⟨expr⟩

⟨test⟩ ∷= ⟨expr⟩ ('=' | '<' | '>') ⟨expr⟩
        | ⟨test⟩ ('and' | 'or') ⟨test⟩
        | 'true' | 'false'


⟨stmt⟩ ∷= 'skip'
        | variable '≔' ⟨expr⟩
        | ⟨stmt⟩ ';' ⟨stmt⟩
        | 'if' ⟨gc_list⟩
        | 'do' ⟨gc_list⟩

⟨gc⟩ ∷= ⟨test⟩ '⇒' ⟨stmt⟩

⟨gc_list⟩ ∷= { ⟨gc⟩ }
#+end_src
That is, the language consists of
- (integer) expressions built from integer constants, variable names,
  and the binary operations addition, multiplication, subtraction and division.
- (boolean) tests built from equality and inequality checks on expressions,
  along with ~and~ and ~or~.
- statements, which may be
  - ~skip~, the empty statement that does nothing,
  - assignment of an expression to a variable,
  - the composition of two statements,
  - the “choice” construct ~if~ applied to a list of guarded commands,
  - the “iteration” construct ~do~ applied to a list of guarded commands,
- and guarded command lists, which are
  a sequence of zero or more guarded commands,
  - where a guarded command consists of a (boolean) test and a statement.

For this language, we use the same notion of (memory) state as in
the beginning of the notes on the /WHILE/ language:
a map or function from variable names to integers.
*We assume for this language that variables are always initialised to 0*.

The semantics of the expressions, tests and
the ~skip~, assignment and composition statements
are intended to be similar to those of /WHILE/ as described in lecture.

The semantics of the ~if~ and ~do~ constructs on guarded command lists
are as noted in homework 9, which discussed the guarded command.
One important note: in both cases, if the guarded command list
is empty, the result should be to “do nothing”.

** /GCLe/
:PROPERTIES:
:CUSTOM_ID: /GCLe/
:END:

The language /GCLe/ is obtained from /GCL/ by adding these productions
to grammer.
#+begin_src text
⟨program⟩ ∷= ⟨globals⟩ ⟨stmt⟩

⟨globals⟩ ∷= 'global' { variable }

⟨stmt⟩ ∷= 'local' variable 'in' ⟨stmt⟩
#+end_src

The intent is that a /program/ now consists of
a list of global variables followed by a statement,
which we may call the “body” of the program.

Additionally, we add a new kind of statement for declaring
local variables.

With these constructs in place, we may now discuss
whether a given program is /well-scoped/;
that is, if every variable used in the program is either
- a global variable, or
- a local variable declared by some wrapping ~local~ statement.

We will assume in the semantics that all programs are well-scoped,
and we can make use of a more precise notion of memory state;
a memory state is some mapping from /variables which are in scope/ to
values. Variables which are not in scope are not handled
by such a memory state.

* Part 1 – Representations of /GCL/ and a small extension [10 marks]
:PROPERTIES:
:CUSTOM_ID: Part-1-–-Representations-of-/GCL/-and-a-small-extension
:END:

In Ruby and in Clojure, create a representation of
the language /GCL/ described in part 0.

In Ruby, define the types ~GCExpr~, ~GCTest~ and ~GCStmt~,
with the following subclasses.
- ~GCExpr~ has subclasses
  - ~GCConst~, the constructor of which takes a single integer argument,
  - ~GCVar~, the constructor of which takes a symbol for the variable name,
  - ~GCOp~, the constructor of which has as its first two arguments are ~GCExpr~'s
    and as its third argument a symbol,
    which is intended to be one of ~:plus~, ~:times~, ~:minus~ or ~:div~.
- ~GCTest~ has subclasses
  - ~GCComp~, the constructor of which has as its first two arguments ~GCExpr~'s
    and as its third argument a symbol,
    which is intended to be one of ~:eq~, ~:less~ or ~:greater~,
  - ~GCAnd~ and ~GCOr~, the constructors of which take as arguments +two ~GCExpr~'s+ two ~GCTest~'s
    (corrected December 16th.)
  - ~GCTrue~ and ~GCFalse~, the constructor of which (if it exists) takes no arguments.
- ~GCStmt~ has subclasses
  - ~GCSkip~, the constructor of which (if it exists) takes no arguments.
  - ~GCAssign~, the constructor of which takes as arguments
    a symbol for the variable name and a ~GCExpr~.
  - ~GCCompose~, the constructor of which takes two ~GCStmt~'s as arguments,
  - ~GCIf~ and ~GCDo~, the constructors of which
    take a list of ~GCTest~ and ~GCStmt~ pairs
    (pairs being lists of two elements.)
  
Wrap all of these definitions inside a ~module~ named ~GCL~.
(This is to avoid name clashes with definitions requested below.)

In Clojure, define /records/ (documentation and examples
[[https://clojuredocs.org/clojure.core/defrecord][here]]) for each kind of expression, test and statement
(using the same naming as in Ruby.)
There is no need to define the ~GCExpr~, ~GCTest~ and ~GCStmt~ types themselves;
only the subtypes as records.

Then, in Ruby, create a separate representation of
the language /GCLe/ described in part 0.
Create a class ~GCProgram~ to represent programs,
the constructor of which takes as its first argument
a list of symbols for the global variable names,
and as its second argument a ~GCStmt~.
Also add an additional subclass to ~GCStmt~, ~GCLocal~,
the constructor of which takes as its first argument a symbol
for the variable name and as its second argument a ~GCStmt~.
Wrap all of these definitions inside a ~module~ named ~GCLe~.

* Part 2 – A stack machine for /GCL/ in Ruby              [25 marks]
:PROPERTIES:
:CUSTOM_ID: Part-2-–-A-stack-machine-for-/GCL/-in-Ruby
:END:

Within the ~GCL~ module, define a method ~stackEval~ on ~GCL~'s,
which carries out the evaluation of a ~GCStmt~ using a stack machine.

The stack machine in question should really be a method
taking three arguments:
1. the command stack (implemented using a list),
2. the results stack (implemented a list), and
3. the memory state (implemented using a lambda; that is, a block.)

The method should return an updated state
(that is, another lambda/block.)

(Added December 11th.)
As part of the ~GCL~ module,
also define a method ~emptyState~ which takes no arguments and
- which returns a lambda for the empty memory state function
  - (that is, a lambda that maps all arguments to ~0~),
and a method ~updateState~ which takes 3 arguments;
- a lambda (for the previous memory state),
- a variable name (i.e., a symbol), and
- an integer.
Then ~updateState(sigma,x,n)~ returns a lambda
which maps ~x~ to ~n~, and any other variable
to the same value as the lambda ~sigma~.
(Technically, only the ~emptyState~ method is required to be
 as described for the testing.
 But a method similar to ~updateState~ will be necessary
 in your ~stackEval~ method.)

* Part 3 – The small-step semantics of /GCL/ in Clojure   [25 marks]
:PROPERTIES:
:CUSTOM_ID: Part-3-–-The-small-step-semantics-of-/GCL/-in-Clojure
:END:

Define in Clojure a function ~reduce~ which takes
a /GCL/ statement and a memory state
(a function mapping symbols, representing the variable names, to integers)
and performs /one step/ of the computation, returning the
remaining code to be run and the updated memory state.

(Added December 11th.)
Also define functions ~emptyState~ and ~updateState~ for use
with your ~reduce~ function.
These should behave equivalently to the methods of the same name
described in part 2 (returning anonymous functions.)
(Once again, only the ~emptyState~ method is needed
 during testing.)

* Part 4 – The big-step semantics of /GCLe/ in Ruby       [40 marks]
:PROPERTIES:
:CUSTOM_ID: Part-4-–-The-big-step-semantics-of-/GCLe/-in-Ruby
:END:

This portion of the assignment should be done in
the ~GCLe~ module created in part 1.

Begin by defining a method ~wellScoped~ [20 marks] which checks that
all variables appearing within the body of a ~GCProgram~
(either in an expression or on the left side of an assignment)
are /within scope/ at the point of their use;
that is, either the variable is one declared to be ~global~,
or there is a ~local~ statement for that variable wrapping the use.
- This method
  +should take a ~GCStmt~ as its only argument+
  should take a ~GCProgram~ as its only argument,
  and return a boolean (Corrected December 16th.)
- Hint: This operation is similar to typechecking.
  Use your experience working with ~typeOf~ as a starting point.
  - Helper methods are always permitted.

Then define the semantics of the language,
this time defining a method ~eval~ [20 marks] directly
(without making use of a stack machine.)
That is, define the /big-step/ semantics of the language
(remember that big-step semantics are called evaluation semantics.)
- This method also should take a ~GCStmt~ as its only argument.
  It should return a ~Hash~ mapping the ~global~ variable names
  to integers.

You may decide what the behaviour is for programs which
do not initialise variables before their first use.
- Your choice may be judged in the marking.
  - It is suggested that such programs “fail gracefully”,
    reporting an error that a variable was used before initialisation.
  - Otherwise, it's suggested that they behave as predictably as possible.

(Added December 11th.)
Because the ~eval~ method does not require a “state” argument,
in this part the tests do not rely upon the ~emptyState~ method
(or the ~updateState~ method.) But you will still need
to define similar methods.

* Part 5 – /GCLe/ in Clojure
:PROPERTIES:
:CUSTOM_ID: Part-5-–-/GCLe/-in-Clojure
:END:

/As a bonus/, repeat part 4 in Clojure.

Place the code for this portion in a file ~a3b.clj~.

This time, you may choose the underlying approach to the operational semantics
(you do not have to use big-step semantics.)

Document this portion especially well, and include your own
tests in a file ~a3bt.clj~. This file should output the results of the tests
when executed using ~cat a3bt.clj | lein~ from the command line.

* Submission checklist
:PROPERTIES:
:CUSTOM_ID: Submission-checklist
:END:

For your convenience, this checklist is provided
to track the files you need to submit.
Use it if you wish.
#+begin_src text
- [ ] Documentation; one of
  - [ ] README.html
  - [ ] README.pdf
  - [ ] README.md
  - [ ] README.org
- [ ] Code files
  - [ ] a3.rb
  - [ ] a3.clj
- [ ] Part 2 tests
  - [ ] a3p2_test.rb tests have passed! (No submission needed.)
- [ ] Part 3 tests
  - [ ] a3_test.clj tests have passed! (No submission needed.)
- [ ] Part 4 tests
  - [ ] a3p4_test.rb tests have passed! (No submission needed.)
- [ ] Part 5 (Bonus)
  - [ ] a3b.clj
  - [ ] a3bt.clj
#+end_src

* Testing
:PROPERTIES:
:CUSTOM_ID: Testing
:END:

Unit tests for the requested types, methods and predicates
are available here.
- [[./testing/a3/a3p2_test.rb][a3p2_test.rb]]
- [[./testing/a3/a3p4_test.rb][a3p4_test.rb]]
- [[./testing/a3/a3_test.clj][a3_test.clj]]
The contents of the unit test files are also repeated below.

The tests can be run by placing the test files
in the same directory as your code files.

To run the tests for the Ruby portions,us the commands
#+begin_src shell
ruby a3_test.rb
#+end_src

To run the tests for the Clojure portions,us the commands
#+begin_src shell
cat a3_test.clj | lein repl
#+end_src

#+begin_center
*You are strongly encouraged to add your own additional test cases*
*to those provided for you.*

The provided test cases check a very minimal amount!
#+end_center

** Automated testing via Docker
:PROPERTIES:
:CUSTOM_ID: Automated-testing-via-Docker
:END:

The Docker setup and usage scripts are available at the following links.
Their contents are also repeated below.
- [[./testing/a3/Dockerfile][Dockerfile]]
- [[./testing/a3/docker-compose.yml][docker-compose.yml]]
- [[./testing/a3/setup.sh][setup.sh]]
- [[./testing/a3/run.sh][run.sh]]
Place them into your ~a3~ directory where your code files
and the test files (linked to above) exist,
then run ~setup.sh~ and ~run.sh~.

Note that the use of the ~setup.sh~ and ~run.sh~ scripts assumes
that you are in a ~bash~ like shell; if you are on Windows,
and not using WSL or WSL2, you may have
to run the commands contained in those scripts manually.

** The tests
:PROPERTIES:
:CUSTOM_ID: The-tests
:END:

*** Ruby
:PROPERTIES:
:CUSTOM_ID: Ruby
:END:

[[./testing/a3p2_test.rb][a3p2_test.rb]]
#+begin_src ruby :tangle ./testing/a3/a3p2_test.rb
require "test/unit"
require_relative "a3"
include GCL

class SimpleTests < Test::Unit::TestCase
  def test_assign_zero
    constant_one = GCConst.new(1)
    assign_constant_one = GCAssign.new(:z, constant_one)
    updated_state = stackEval([assign_constant_one], [], emptyState)

    assert_equal(1, updated_state.call(:z), "Assigning 1 to z did not work.")
  end

  def test_two_possible_assignments_part1
    constant_one = GCConst.new(1)
    constant_two = GCConst.new(2)
    assign_constant_one = GCAssign.new(:y, constant_one)
    assign_constant_two = GCAssign.new(:y, constant_two)
    branch = GCIf.new([[GCTrue.new, assign_constant_one],
                       [GCTrue.new, assign_constant_two]])
    
    # Run the program 50 times, to make relatively sure
    # both possible results (y = 1 and y = 2) are seen.
    results = []
    50.times do results.push(GCL::stackEval([branch], [], emptyState).call(:y)) end

    assert_equal(true,results.include?(1), "An if statement which randomly assigns 1 or 2 never assigned 1.")
  end

  def test_two_possible_assignments_part2
    constant_one = GCConst.new(1)
    constant_two = GCConst.new(2)
    assign_constant_one = GCAssign.new(:y, constant_one)
    assign_constant_two = GCAssign.new(:y, constant_two)
    branch = GCIf.new([[GCTrue.new, assign_constant_one],
                       [GCTrue.new, assign_constant_two]])
    
    # Run the program 50 times, to make relatively sure
    # both possible results (y = 1 and y = 2) are seen.
    results = []
    50.times do results.push(GCL::stackEval([branch], [], emptyState).call(:y)) end

    assert_equal(true,results.include?(2), "An if statement which randomly assigns 1 or 2 never assigned 2.")
  end

  def test_oscillating
    x_var = GCVar.new(:x)
    assign_x_5 = GCAssign.new(:x,GCConst.new(5))
    inc_x_1 = GCAssign.new(:x,GCOp.new(x_var,GCConst.new(1),:plus))
    dec_x_1 = GCAssign.new(:x,GCOp.new(x_var,GCConst.new(1),:minus))
    check_x_less_8    = GCComp.new(x_var,GCConst.new(8),:less)
    check_x_greater_2 = GCComp.new(x_var,GCConst.new(2),:greater)
    check_x_within_3_7 = GCAnd.new(check_x_greater_2,check_x_less_8)
    
    # A program to increment or decrement the value of variable x
    # randomly until it is less than 3 or greater than 7,
    oscillate_x = GCDo.new([[check_x_within_3_7, dec_x_1],
                            [check_x_within_3_7, inc_x_1]])

    assign_then_oscillate = GCCompose.new(assign_x_5, oscillate_x)
    
    # Run the program 50 times, to make relatively sure
    # both possible results (x = 2 and x = 8) are seen.
    results = []
    50.times do results.push(GCL::stackEval([assign_then_oscillate], [], emptyState).call(:x)) end

    assert_equal(true,results.include?(2), "A do statement which oscillates the value of x between 2 and 8 never got to 2.")
    assert_equal(true,results.include?(8), "A do statement which oscillates the value of x between 2 and 8 never got to 8.")
  end

end
#+end_src

[[./testing/a3p4_test.rb][a3p4_test.rb]]
#+begin_src ruby :tangle ./testing/a3/a3p4_test.rb
require "test/unit"
require_relative "a3"
include GCLe

class SimpleTests < Test::Unit::TestCase
  
  def test_wellscoped1
    assert_equal(true, GCLe::wellScoped(GCProgram.new([:x,:y], GCAssign.new(:x, GCVar.new(:x)))),
                 "global x y; x := x should be well scoped.")
  end

  def test_wellscoped2
    assert_equal(true, GCLe::wellScoped(GCProgram.new([:x,:y], GCAssign.new(:x, GCVar.new(:y)))),
                 "global x y; x := y should be well scoped.")
  end

  def test_wellscoped3
    assert_equal(true, GCLe::wellScoped(GCProgram.new([], GCLocal.new(:x, GCAssign.new(:x, GCVar.new(:x))))),
                 "global; local x in x := x should be well scoped. TEST UPDATED DEC16.")
  end

  def test_not_wellscoped1
    assert_equal(false, GCLe::wellScoped(GCProgram.new([:y], GCAssign.new(:x, GCVar.new(:x)))),
                 "global y; x := x should NOT be well scoped.")
  end

  def test_not_wellscoped2
    assert_equal(false, GCLe::wellScoped(GCProgram.new([:x], GCAssign.new(:x, GCVar.new(:y)))),
                 "global x; x := y should NOT be well scoped.")
  end

  def test_not_wellscoped3
    assert_equal(false, GCLe::wellScoped(GCProgram.new([], GCLocal.new(:y, GCAssign.new(:x, GCVar.new(:y))))),
                 "global; local y in x := y should NOT be well scoped. DESCRIPTION UPDATED DEC16.")
  end

  def test_assign_zero
    constant_one = GCConst.new(1)
    assign_constant_one = GCAssign.new(:z, constant_one)
    updated_state = GCLe::eval(GCProgram.new([:z],assign_constant_one))

    assert_equal(1, updated_state[:z], "Assigning 1 to z did not work.")
  end

  def test_two_possible_assignments_part1
    constant_one = GCConst.new(1)
    constant_two = GCConst.new(2)
    assign_constant_one = GCAssign.new(:t, constant_one)
    assign_constant_two = GCAssign.new(:t, constant_two)
    branch = GCIf.new([[GCTrue.new, assign_constant_one],
                       [GCTrue.new, assign_constant_two]])
    assign_t_to_y = GCAssign.new(:y, GCVar.new(:t))
    the_program = GCProgram.new([:y],GCLocal.new(:t,GCCompose.new(branch, assign_t_to_y)))

    # Run the program 50 times, to make relatively sure
    # both possible results (y = 1 and y = 2) are seen.
    results = []
    50.times do results.push(GCLe::eval(the_program)[:y]) end
  
    assert_equal(true,results.include?(2), "An if statement which randomly assigns 1 or 2 never assigned 1.")
  end

  def test_two_possible_assignments_part2
    constant_one = GCConst.new(1)
    constant_two = GCConst.new(2)
    assign_constant_one = GCAssign.new(:t, constant_one)
    assign_constant_two = GCAssign.new(:t, constant_two)
    branch = GCIf.new([[GCTrue.new, assign_constant_one],
                       [GCTrue.new, assign_constant_two]])
    assign_t_to_y = GCAssign.new(:y, GCVar.new(:t))
    the_program = GCProgram.new([:y],GCLocal.new(:t,GCCompose.new(branch, assign_t_to_y)))

    # Run the program 50 times, to make relatively sure
    # both possible results (y = 1 and y = 2) are seen.
    results = []
    50.times do results.push(GCLe::eval(the_program)[:y]) end
  
    assert_equal(true,results.include?(0), "An if statement which randomly assigns 1 or 2 never assigned 2.")
  end
  
  def test_oscillating
    x_var = GCVar.new(:x)
    assign_x_5 = GCAssign.new(:x,GCConst.new(5))
    inc_x_1 = GCAssign.new(:x,GCOp.new(x_var,GCConst.new(1),:plus))
    dec_x_1 = GCAssign.new(:x,GCOp.new(x_var,GCConst.new(1),:minus))
    check_x_less_8    = GCComp.new(x_var,GCConst.new(8),:less)
    check_x_greater_2 = GCComp.new(x_var,GCConst.new(2),:greater)
    check_x_within_3_7 = GCAnd.new(check_x_greater_2,check_x_less_8)
    
    # A program to increment or decrement the value of variable x
    # randomly until it is less than 3 or greater than 7,
    oscillate_x = GCDo.new([[check_x_within_3_7, dec_x_1],
                            [check_x_within_3_7, inc_x_1]])

    assign_then_oscillate = GCCompose.new(assign_x_5, oscillate_x)

    the_program = GCProgram.new([:x],assign_then_oscillate)

    # Run the program 50 times, to make relatively sure
    # both possible results (x = 2 and x = 8) are seen.
    results = []
    50.times do results.push(GCLe::eval(the_program)[:x]) end
  
    assert_equal(true,results.include?(2), "A do statement which oscillates the value of x between 2 and 8 never got to 2.")
    assert_equal(true,results.include?(8), "A do statement which oscillates the value of x between 2 and 8 never got to 8.")
  end

end
#+end_src

*** Clojure
:PROPERTIES:
:CUSTOM_ID: Clojure
:END:

[[./testing/a3_test.clj][a3_test.clj]]
#+begin_src clojure :tangle ./testing/a3/a3_test.clj
(ns testing)
(use 'clojure.test)
(load-file "a3.clj")

;; A function to compute a given expression a number of times,
;; creating a list of the results.
;; Used to test the non-determinacy of GC programs involvings ifs and dos.
(defn times [n f]
  "Repeatedly evaluate `f` `n` times and concatenate together the results."
  (concat
   (repeatedly n #(eval f))))



(deftest test-state-assign-constant-one
  (is (= 1        ((.sig  (reduce (Config. (GCAssign. :x (GCConst. 1)) emptyState))) :x))))

(deftest test-stmt-assign-constant-one
  (is (= (GCSkip.) (.stmt (reduce (Config. (GCAssign. :x (GCConst. 1)) emptyState))))))

(deftest test-two-possible-branches-first
  (let [branch (GCIf. [[(GCTrue.) (GCAssign. :x (GCConst. 0))] [(GCTrue.) (GCAssign. :x (GCConst. 1))]])]
    (is (some #(= (GCAssign. :x (GCConst. 0)) %) (times 50 `(.stmt (reduce (Config. ~branch emptyState))))))))

(deftest test-two-possible-branches-second
  (let [branch (GCIf. [[(GCTrue.) (GCAssign. :x (GCConst. 0))] [(GCTrue.) (GCAssign. :x (GCConst. 1))]])]
    (is (some #(= (GCAssign. :x (GCConst. 1)) %) (times 50 `(.stmt (reduce (Config. ~branch emptyState))))))))

;; If we define `test-ns-hook`, it is called when running `run-tests`,
;; instead of just calling all tests in the namespace.
;; This lets us control the order of the tests.
(deftest test-ns-hook
  (test-state-assign-constant-one)
  (test-stmt-assign-constant-one)
  (test-two-possible-branches-first))

(run-tests 'testing)
#+end_src

** The Docker setup
:PROPERTIES:
:CUSTOM_ID: The-Docker-setup
:END:

[[./testing/a2/Dockerfile][Dockerfile]]
#+begin_src docker :tangle ./testing/a3/Dockerfile
# Define the argument for openjdk version
ARG OPENJDK_TAG=8u232

FROM clojure:openjdk-8

# Install Ruby
RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests curl bzip2 build-essential libssl-dev libreadline-dev zlib1g-dev && \
    rm -rf /var/lib/apt/lists/* && \
    curl -L https://github.com/rbenv/ruby-build/archive/v20201118.tar.gz | tar -zxvf - -C /tmp/ && \
    cd /tmp/ruby-build-* && ./install.sh && cd / && \
    ruby-build -v 2.7.2 /usr/local && rm -rfv /tmp/ruby-build-*

# Set the name of the maintainers
MAINTAINER Habib Ghaffari Hadigheh, Mark Armstrong <ghaffh1@mcmaster.ca, armstmp@mcmaster.ca>

# Set the working directory
WORKDIR /opt/a3
#+end_src

[[./testing/a2/docker-compose.yml][docker-compose.yml]]
#+begin_src yaml :tangle ./testing/a3/docker-compose.yml
version: '2'
services:
  service:
    build: .
    image: 3mi3_a3_docker_image
    volumes:
      - .:/opt/a3
    container_name: 3mi3_a3_container
    command: bash -c
      "echo 'Ruby part 2 testing' ;
       echo '----------------------------------------------------------------------' ;
       timeout 2m ruby a3p2_test.rb ;
       echo '----------------------------------------------------------------------' ;
       printf '\\n\\n\\n' ;
       echo 'Ruby part 4 testing' ;
       echo '----------------------------------------------------------------------' ;
       timeout 2m ruby a3p4_test.rb ;
       echo '----------------------------------------------------------------------' ;
       printf '\\n\\n\\n' ;
       echo 'Clojure testing' ;
       echo '----------------------------------------------------------------------' ;
       cat a3_test.clj | timeout 2m lein repl ;
       echo '----------------------------------------------------------------------'"
#+end_src

[[./testing/a2/setup.sh][setup.sh]]
#+begin_src shell :tangle ./testing/a3/setup.sh :tangle-mode (identity #o755)
docker-compose build --force-rm
#+end_src

[[./testing/a2/run.sh][run.sh]]
#+begin_src shell :tangle ./testing/a3/run.sh :tangle-mode (identity #o755)
# Run the container
docker-compose up --force-recreate
# Stop the container after finishing the test run
docker-compose stop -t 1
#+end_src
