#+Title: Infinite data in Scala
#+Author: Mark Armstrong
#+Description: We discuss the notion of “infinite data”, and show
#+Description: how we can represent such data in Scala.
#+SETUPFILE: ../../org-html-themes/setup/theme-readtheorg-local.setup

* LaTeX settings                                :noexport:

#+LaTeX_header: \usepackage{unicode-math}
#+LaTeX_header: \usepackage{unicode}

* Introduction
:PROPERTIES:
:CUSTOM_ID: Introduction
:END:

These notes were created for, and in some parts *during*,
the lecture on October 2nd and the following tutorials.

* Motivation
:PROPERTIES:
:CUSTOM_ID: Motivation
:END:

In our current lectures, we have been discussing the λ-calculus,
and as of the time of writing this, we are about to discuss
reduction strategies.

The reduction strategies used in the λ-calculus
correspond to the parameter-passing methods
used in conventional programming languages.

* Call by value and call by name
:PROPERTIES:
:CUSTOM_ID: Call-by-value-and-call-by-name
:END:

Today, we are interested in the
“call by value” and “call by name”
reduction strategies/parameter-passing methods.
- Under “call by value” semantics,
  a function application is only evaluated after
  its arguments have been reduced to values.
- Under “call by name” (or “call by need”) semantics,
  no arguments in a function application are evaluated before
  the function is applied.
  - (And no reduction is allowed inside abstractions.)

(Under both schemes, the leftmost, outermost valid reduction is done first.)

We can see the difference by considering a sample redex
in the λ-calculus.
#+begin_src text
(λ x → x x)((λ y → y) (λ z → z))
#+end_src
Notice that there are two possible applications to carry out;
applying ~λ z → z~ to ~λ y → y~, or
applying ~(λ y → y) (λ z → z)~ to ~λ x → x x~.

A call-by-value semantics requires that the right side be evaluated first;
“a function application is only evaluated
after its arguments have been reduced to values”.
So we cannot perform the outermost application until the term on the right
is reduced.
#+begin_src text
  (λ x → x x)((λ y → y) (λ z → z))
⟶ (λ x → x x)(λ z → z)
⟶ (λ z → z) (λ z → z)
→ λ z → z
= id
#+end_src

A call-by-name semantics instead requires that the outside
application is evaluated first;
“no arguments in a function application are evaluated before
the function is applied”.
So we cannot perform the application in the term on the right
until we apply the outermost application.
#+begin_src text
  (λ x → x x)((λ y → y) (λ z → z))
⟶ ((λ y → y) (λ z → z)) ((λ y → y) (λ z → z))
→ (λ z → z) ((λ y → y) (λ z → z))
→ (λ y → y) (λ z → z)
→ λ z → z
= id
#+end_src

* Parameter passing in Scala
:PROPERTIES:
:CUSTOM_ID: Parameter-passing-in-Scala
:END:

By default, Scala uses a call-by-value strategy.
#+begin_src amm :results none
def f(x: Int): Unit = { println("Called f with argument"); println(x) }
#+end_src

You may /opt-in/ to call by name using what they call “by name parameters”;
simply prepend ~=>~ to the type.
#+begin_src amm :results none
def g(y: => Int) : Unit = { println("Called g with argument"); println(y) }
#+end_src

Let us create a value that is not immediately evaluated,
and which communicates when it is evaluated,
so we can use it as an argument to test out our above definitions.
One way to do this is by defining it as a method with no parameters.
#+begin_src amm :results none
def x: Int = { println("Evaluated x"); 1 }
#+end_src
:TODO: explain the term lazy

Scala also has “lazy” values, which are not evaluated until used.
:TODO: how is this different than x?
#+begin_src amm :results none
lazy val y: Int = { println("Evaluated y"); 2 }
#+end_src

* What's the point?
:PROPERTIES:
:CUSTOM_ID: What's-the-point?
:END:

Why do we want to be allowed to use call by name semantics
and lazy values?

It may make some tasks easier conceptually;
for instance, one common use case involves a function
on the natural numbers, such as one that returns the “nth” prime.

We could certainly write such a function,
but an alternative approach is to /lazily/ construct
the list of all primes by /filtering/ the list of all naturals.
Since it is lazily constructed, no space is used
until we begin to look up elements in the list.
(Code courtesy of this [[https://stackoverflow.com/q/15594227/2041536][StackOverflow]] post,
modified to work with ~LazyList~.)
#+begin_src amm :results none
lazy val ps: LazyList[Int] =
  2 #:: LazyList.from(3).filter(i => ps.takeWhile{j => j * j <= i}.forall{ k => i % k > 0});
#+end_src

And, because lazy data is not re-evaluated,
once we have looked up elements, the already calculated portion
of the list is automatically cached for us!
This is (in some instances) an advantage over the function.

Now, we have subtlely used another concept enabled by lazy values
and call-by-name semantics in the above: an infinite list!

* Infinite data!
:PROPERTIES:
:CUSTOM_ID: Infinite-data!
:END:

** Not with lists…
:PROPERTIES:
:CUSTOM_ID: Not-with-lists…
:END:

When we discuss lists in computer science,
they are usually defined as having /finite/ length.

Let us try to break away from that convention.
We can define an infinite list by using recursion.
But what does you intuition tell you will happen here?
#+begin_src amm :results none
lazy val ones: List[Int] = 1 :: ones
#+end_src

** …instead, with lazy lists or streams!
:PROPERTIES:
:CUSTOM_ID: …instead,-with-lazy-lists-or-streams!
:END:

The [[https://www.scala-lang.org/api/current/scala/collection/immutable/LazyList.html][lazy list]] type and
the [[https://www.scala-lang.org/api/current/scala/collection/immutable/Stream.html][stream]] type (now deprecated in favour of lazy lists)
actually allow us to define such lists.
#+begin_src amm :results none
lazy val ones: LazyList[Int] = 1 #:: ones
#+end_src

We can then make these lists more interesting
by filtering, zipping, etc.;
or by writing more interesting recursive definitions.

* +(Not)+ Implementing our own infinite datatypes
:PROPERTIES:
:CUSTOM_ID: Implementing-our-own-infinite-datatypes
:END:

** The approach
:PROPERTIES:
:CUSTOM_ID: The-approach
:END:

To implement such a type ~T~ with the algebraic datatype approach
we have been using, we may use (recursive) parameters
of the form ~Unit => T~.

Function parameters are /never/ evaluated until
the function is invoked (called.)
*This will approach will work in any language with
higher-order functions.*

For example, we can define our own variant of streams.
#+begin_src amm :results none
sealed trait Stream[+A] // Stream is covariant (marked by the +)
case object SNil extends Stream[Nothing] // The singleton Nil object
case class Cons[A](a: A, f: Unit => Stream[A]) extends Stream[A]
#+end_src

** ~case object~?
:PROPERTIES:
:CUSTOM_ID: ~case-object~?
:END:

We adopt here and now the convention of making our base case
a ~case object~, rather than a ~case class~.
The difference is that there is exactly one instance of
a ~case object~ (it is a singleton),
whereas there can be many of a ~case class~.
Since there can only be one instance of ~Nil~,
this instance needs to be a member of ~Stream[A]~ for any ~A~,
so it must be a member of ~Stream[Nothing]~, since ~Nothing~ is
the only subtype of all types.
This does require us to mark ~Stream~ as /covariant/,
meaning that ~Stream[A]~ is a subtype of ~Stream[B]~ is ~A~ is a subtype of ~B~.
(We will discuss subtyping, variance and covariance
in more detail later in the course.)

** Defining some methods on our streams
:PROPERTIES:
:CUSTOM_ID: Defining-some-methods-on-our-streams
:END:

#+begin_src amm :results none
def constantStream[A](a: A): Stream[A] = Cons(a, _ => constantStream(a))
#+end_src

#+begin_src amm :results none
def take[A](n: Int, s: Stream[A]): List[A] = s match {
  case SNil => Nil
  case Cons(a,f) => n match {
    case n if n > 0 => a :: take(n-1,f())
    case _ => Nil
    }
  }
#+end_src

