#+Title: Notation and Conventions
#+Author: Mark Armstrong
#+Description: A living list of notation and conventions
#+Description: used in my principles of programming course.

* Writing style

This section discusses some particulars of my writing style
I have found sometimes need explanation.

** Parentheses and en dashes

Parentheses inside sentences I use to indicate optional words.
The sentence may be read sensibly without the parenthesised portion.
The parenthesised portions are intended to offer additional context.
#+begin_example
In particular, they are often used to expand abbreviations
such as CFG (context-free grammar)
in their first use (or first use after a while).
#+end_example

For the other common use of parentheses, to wrap asides
(or parenthetical statements) I use em dashes, written —.
These are portions of sentences that somewhat deviate
from the topic of the sentence.
Note the difference between the em dash, —, and the hyphen, -,
or the (occasionally used in my writing) en dash, – .
#+begin_example
In a sentence containing an aside in the middle
—such as this one—
has the em dashes tightly wrapping the aside.
In case the aside ends the sentence, the trailing em dash is omitted
—as in this case.
#+end_example

* Variable conventions

:TODO: Refer to Types and Programming Languages

* Abbreviations

** General use

- e.g. :: for instance
- i.e. :: that is
- s.t. :: such that
- w/o :: without
- w.r.t. :: with respect to
- w/ :: with
