#+Title: A typed λ-calculus, /TL/
#+Subtitle: Principles of Programming Languages
#+Author: Mark Armstrong
#+Date: Fall 2020
#+Description: Extending our lambda calculus with type checking (enforcement).
#+Options: toc:nil

* HTML settings                                 :noexport:

** Reveal settings

#+Reveal_root: ./reveal.js
#+Reveal_init_options: width:1600, height:900, controlsLayout:'edges',
#+Reveal_init_options: margin: 0.1, minScale:0.125, maxScale:5,
#+Reveal_init_options: mouseWheel: true
#+Reveal_extra_css: local.css

# #+HTML: <script src="https://cdnjs.cloudflare.com/ajax/libs/headjs/0.96/head.min.js"></script>

* LaTeX settings                                :noexport:

#+LaTeX_header: \usepackage[a4paper,total={7in,10in}]{geometry}

#+LaTeX_header: \usepackage{amsthm}
#+LaTeX_header: \theoremstyle{definition}
#+LaTeX_header: \newtheorem{definition}{Definition}[section]

#+LaTeX_header: \usepackage{unicode-math}
#+LaTeX_header: \usepackage{unicode}

* Preamble

** Notable references

- Benjamin Pierce,
  “[[https://ebookcentral.proquest.com/lib/mcmu/detail.action?docID=3338823][Types and Programming Languages]]”
  - Chapter 9, Simply Typed Lambda-Calculus
    - Function types, the typing relation
  - Chapter 11, Simple Extensions
    - Unit, Tuples, Sums, Variants, Lists.

** TODO Table of contents

# The table of contents are added using org-reveal-manual-toc,
# and so must be updated upon changes or added last.
# Note that hidden headings are included, and so must be deleted!

#+HTML: <font size="-1">
#+begin_scriptsize
  - [[Preamble][Preamble]]
#+end_scriptsize
#+HTML: </font>

* Introduction

In this section we extend our previously considered
untyped λ-calculus by defining a typing relation,
essentially adding type checking (enforcement).

We then investigate adding some
algebraic type formers to the language.
This involves the introduction of a rudimentary form
of pattern matching.

* Recall: The untyped λ-calculus

** Preamble                                    :ignore:

Recall from section 3 of the notes the syntax
of our untyped λ-calculus, /UL/.
#+begin_src text
⟨term⟩ ∷= var | λ var → ⟨term⟩ | ⟨term⟩ ⟨term⟩
#+end_src

Recall that in this pure untyped λ-calculus,
everything is a function, and abstractions
(terms of the form ~λ x → t~) are /values/.

** The call-by-value semantics of the untyped λ-calculus

The call-by-value semantics we described in section 3 of the notes
can be more succinctly described using inference rules.
- In fact, we only need three rules.

- Here the arrow ~⟶~ defines a /reduction/ relation,
  meaning that we may need to perform several ~⟶~ “steps” to fully
  evaluate a term.
- The (meta)variables ~t₁~, ~t₂~, etc., range over λ-terms, and
- the (meta)variables ~v₁~, ~v₂~, etc., range over λ-terms /which are values/.
#+begin_src text
  t₁  ⟶  t₁′
––––––––––––––––––– reduce-appˡ
 t₁ t₂  ⟶  t₁′ t₂

 
  t₂  ⟶  t₂′
––––––––––––––––––– reduce-appʳ
 v₁ t₂  ⟶  v₁ t₂′


–––––––––––––––––––––––––––––– apply
(λ x → t) v  ⟶  t[x ≔ v]
#+end_src

** Only applications reduce

@@latex:\iffalse@@
#+begin_src text
  t₁  ⟶  t₁′                             t₂  ⟶  t₂′                   
––––––––––––––––––– reduce-appˡ        ––––––––––––––––––– reduce-appʳ
 t₁ t₂  ⟶  t₁′ t₂                       v₁ t₂  ⟶  v₁ t₂′              


 
             –––––––––––––––––––––––––––––– apply
             (λ x → t) v  ⟶  t[x ≔ v]
#+end_src
@@latex:\fi@@

Notice, in the above semantics, that the only rules
are for applications; remember that
- variables cannot be reduced, and
- under call-by-value semantics,
  - no evaluations take place inside abstractions, and
  - abstractions are only applied to values.

** Explaining the rules

@@latex:\iffalse@@
#+begin_src text
  t₁  ⟶  t₁′                             t₂  ⟶  t₂′                   
––––––––––––––––––– reduce-appˡ        ––––––––––––––––––– reduce-appʳ
 t₁ t₂  ⟶  t₁′ t₂                       v₁ t₂  ⟶  v₁ t₂′              


 
             –––––––––––––––––––––––––––––– apply
             (λ x → t) v  ⟶  t[x ≔ v]
#+end_src
@@latex:\fi@@

By using our naming conventions, we can see that
- the ~reduce-appˡ~ rule says that
  if ~t₁~ is the left side of an application
  and ~t₁~ reduces to ~t₁′~, then the whole application reduces
  by replacing ~t₁~ with ~t₁′~,
- the ~reduce-appʳ~ rule says that
  if ~t₁~ is the right side of
  an application /whose left side is a value/,
  and ~t₂~ reduces to ~t₂′~, then the whole application reduces
  by replacing ~t₂~ with ~t₂′~, and
- the ~apply~ rule says that if the left side of an application
  is an abstraction, and the right side is a value,
  then the application reduces to the body of the abstraction
  with the value substituted for the abstraction's variable.
  
** Reduction as a function

@@latex:\iffalse@@
#+begin_src text
  t₁  ⟶  t₁′                             t₂  ⟶  t₂′                   
––––––––––––––––––– reduce-appˡ        ––––––––––––––––––– reduce-appʳ
 t₁ t₂  ⟶  t₁′ t₂                       v₁ t₂  ⟶  v₁ t₂′              


 
             –––––––––––––––––––––––––––––– apply
             (λ x → t) v  ⟶  t[x ≔ v]
#+end_src
@@latex:\fi@@

It bears noting that the /reduction relation/ here is,
by design, /deterministic/; given a λ-term ~t~, either
- ~t~ can be reduced by exactly /one/ of the rules above, or
- ~t~ cannot be reduced (is irreducible) (by these semantics.)

A deterministic relation can be expressed as a /function/,
as the following Scala-like pseudocode shows.
#+begin_example amm
def ⟶(t) = t match {
  case t₁ t₂ if t₁ ⟶ t₁′                 => t₁′ t₂
  case v₁ t₂ if isValue(v₁) &&  t₂ ⟶ t₂′ => v₁ t₂′
  case (λ x → t) v if isValue(v)         => t[x ≔ v]
} 
#+end_example

** An example of a reduction sequence

#+begin_src text
  ((λ x → x) (λ y → y)) ((λ z → z) (λ u → u))
⟶⟨ reduce-appˡ ⟩
  (λ y → y) ((λ z → z) (λ u → u))
⟶⟨ reduce-appʳ ⟩
  (λ y → y) (λ u → u)
⟶⟨ apply ⟩
  λ u → u
#+end_src
The final term does not reduce.

Note that we can end with terms which do not reduce, but which
are not values, such as
#+begin_src text
(λ x → x) y
#+end_src
Since free variables are not values (they are not λ-abstractions),
this term does not fit any of the reduction rules.

** Encodings of booleans, natural numbers and pairs

Recall the λ-encodings discussed in notes section 3,
which allow us to represent booleans, natural numbers
and pairs in the pure untyped λ-calculus.
#+begin_src text
tru  = λ t → λ f → t
fls  = λ t → λ f → f
test = λ l → λ m → λ n → l m n
pair = λ f → λ s → λ b → b f s
fst  = λ p → p tru
snd  = λ p → p fls
zero = λ s → λ z → z
scc  = λ n → λ s → λ z → s (n s z)
#+end_src

** Enriching the (syntax of the) calculus

While λ-encodings of data in the pure untyped λ-calculus,
such as those for the booleans, natural numbers and pairs,
do allow us to construct programs working on any type data
we might like, it is usually more convenient
(even in this untyped system)
to instead /enrich/ the calculus with new primitive terms
for the types we want to work with.

We will show here how this can be done for booleans.
The enriched calculus's syntax is then
#+begin_src text
⟨term⟩ ∷= var | λ var → ⟨term⟩ | ⟨term⟩ ⟨term⟩
        | true | false
        | if ⟨term⟩ then ⟨term⟩ else ⟨term⟩
#+end_src

** The semantics of the untyped λ-calculus with booleans

The untyped λ-calculus extended with booleans semantics has,
in addition to the rules ~reduce-appˡ~, ~reduce-appʳ~ and ~apply~,
these rules for the new basic primitive functions.
#+begin_src text
          tᵇ  ⟶  tᵇ′
–––––––––––––––––––––––––––––––––– reduce-if
 if tᵇ t₁ t₂  ⟶  if tᵇ′ t₁ t₂

 

––––––––––––––––––––––––– if-then
 if true t₁ t₂  ⟶  t₁



––––––––––––––––––––––––– if-else
 if false t₁ t₂  ⟶  t₂
#+end_src

* A first typed λ-calculus – the simply typed λ-calculus

** Preamble                                    :ignore:

Starting now, we define the syntax and semantics for several stages
of a typed λ-calculus.
- We begin with a “simply-typed” λ-calculus that has only
  unit and function types, and
- at each stage (in the following sections of these notes),
  we add new primitive terms, new types
  and typing rules, and new semantic rules.

These stages roughly correspond to those given in
Pierce's “Types and Programming Languages” throughout
chapters
- 9, “Simply Typed Lambda-Calculus”, and
- 11, “Simple Extensions”.

For the sake of page space, each stage will only show
the grammar productions and semantic rule which are added,
not the whole grammar or semantics.
- Those will be given at the end.

All semantics in this section are call-by-value semantics.

** Typing rules

Like semantics, the typing rules of a language
are presented here using inference rules.

These inference rules define a typing relation,
written $\_⊢\_:\_$ and read as “entails”.

While the reduction relation, $\_⟶\_$, is a binary relation between terms
- i.e., $\_⟶\_ : \texttt{term} × \texttt{term}$
  - (in fact, since it is a single-valued relation, $\_⟶\_ : \texttt{term} → \texttt{term}$),
the typing relation is a /ternary/ relation between a /typing context/,
a term and a type.
- i.e., $\_⊢\_:\_ \ \ : \ \ \texttt{context} × \texttt{term} × \texttt{type}$
  - (in fact, since it is also a single-valued relation,
    $\_⊢\_:\_ \ \ : \ \ \texttt{context} × \texttt{term} → \texttt{type}$.)

** The typing context

The /typing context/ referred to above is a set
of variable, type pairs, used to /bind/ certain variables to types.
- It can in fact be a sequence or similar datatype;
  so long as we can add and check bindings.

We will write
- ~∅~ for the /empty/ typing context,
- ~Γ,(x : A)~ to /extend/ the typing context ~Γ~ with the additional
  type binding of ~x~ to ~A~, and
- ~(x : A) ∈ Γ~ to check if ~x~ is bound to type ~A~ by the typing context ~Γ~.

** Example typing contexts

For example,
- ~(x : A) ∈ (∅,(z : C),(y : C),(x : A)~) and
- ~(y : C) ∈ (∅,(z : C),(y : C),(x : A)~) and
but
- NOT ~(x : B) ∈ (∅,(z : C),(y : C),(x : A)~) and
- NOT ~(y : B) ∈ (∅,(z : C),(y : C),(x : A)~) and

We generally try avoid having two entries for a variable in the typing context
(such as ~∅,(x : A),(x : B)~ or even ~∅,(x : A),(x : A)~.)
- This will occur in practice if variable names are reused.
In the case that there are two such entries, the later one
“shadows” the earlier one.
- So for instance, ~(x : B) ∈ (∅,(x : A),(x : B))~ and
- NOT ~(x : A) ∈ (∅,(x : A),(x : B))~.
  
** The simply-typed λ-calculus syntax

Our starting point is the simply-typed λ-calculus,
which has only unit and function types.
- For the sake of noting which new terms are values,
  we add a non-terminal called ~⟨value⟩~ to the grammar.
#+begin_src text
⟨term⟩ ∷= var
        | ⟨term⟩ ⟨term⟩
        | ⟨value⟩
        
⟨value⟩ ∷= λ var : ⟨type⟩ → ⟨term⟩
         | unit
         
⟨type⟩ ∷= Unit | ⟨type⟩ → ⟨type⟩
#+end_src

** The simply-typed λ-calculus typing

“If a variable ~x~ is assigned type ~A~ by the context,
then it has that type.”
#+begin_src text
 (x : A) ∈ Γ
––––––––––––––– T-Var
 Γ ⊢ x : A
#+end_src
Notice that otherwise, variables do not typecheck!

“The abstraction of a variable ~x~ of type ~A~ over a term ~t~ has
type ~A → B~ if ~t~ has type ~B~ when assuming ~x~ has type ~A~.” 
#+begin_src text
 Γ,(x : A) ⊢ t : B
––––––––––––––––––––––––––––––– T-Abs
 Γ ⊢ (λ x : A → t) : A → B
#+end_src

“If ~t₁~ has type ~A → B~ and ~t₂~ type ~A~, then applying ~t₁~ to ~t₂~ has type ~B~.”
#+begin_src text
 Γ ⊢ t₁ : A → B    Γ ⊢ t₂ : A
––––––––––––––––––––––––––––––––– T-App
        Γ ⊢ t₁ t₂ : B
#+end_src

“~unit~ has type ~Unit~.” 
#+begin_src text
––––––––––––––––––––––––––––––––– T-Unit
        Γ ⊢ unit : Unit
#+end_src

** The simply-typed λ-calculus semantics

The semantics of the language have not changed,
except that the syntax of the λ-abstraction now
has the type annotation.
#+begin_src text
  t₁  ⟶  t₁′
––––––––––––––––––– reduce-appˡ
 t₁ t₂  ⟶  t₁′ t₂

 
  t₂  ⟶  t₂′
––––––––––––––––––– reduce-appʳ
 v₁ t₂  ⟶  v₁ t₂′


–––––––––––––––––––––––––––––– apply
(λ x : A → t) v  ⟶  t[x ≔ v]
#+end_src

** Exercise: Why do we need a ~Unit~ type in the simply-typed λ-calculus?

Recall that in the untyped λ-calculus,
the only values were abstractions; all data was functions.

Why do we add a ~Unit~ type in the simply-typed λ-calculus?
Is it required for some reason?

** Exercise: Type some terms

Using the typing rules above, determine the types of the following
simply-typed λ-calculus terms.
(You should try to give a derivation of the type using the rules.)

1. ~(λ x : Unit → x)~.
2. ~(λ x : Unit → x) (unit)~.
3. ~(λ x : (Unit → Unit) → λ y : Unit → x y) (λ z : Unit → unit)~.
4. ~(λ x : (Unit → Unit) → λ y : Unit → x y) (λ z : Unit → unit) (unit)~.
   
For these terms, try to justify which portion(s) of the term
causes it not to typecheck.
1. ~x~.
2. ~(λ x : Unit → x) (λ x : Unit → x)~.

* Adding natural numbers and booleans

** Preamble                                    :ignore:

We begin our extensions to the simply-typed λ-calculus
with the natural numbers and booleans,
convenient types to have for many simply computing problems.

** Syntax for natural numbers and booleans

Recall that these productions are only those being added;
the productions from [[The simply-typed λ-calculus syntax]] are
assumed to still be in place.

#+begin_src text
⟨term⟩ ∷= suc ⟨term⟩
        | pred ⟨term⟩
        | iszero ⟨term⟩
        | if ⟨term⟩ then ⟨term⟩ else ⟨term⟩

⟨value⟩ ∷= suc ⟨value⟩
         | zero
         | true
         | false

⟨type⟩ ∷= Nat | Bool
#+end_src

** Notes about the syntax

@@latex:\iffalse@@
#+begin_src text
⟨term⟩ ∷= suc ⟨term⟩
        | pred ⟨term⟩
        | iszero ⟨term⟩
        | if ⟨term⟩ then ⟨term⟩ else ⟨term⟩

⟨value⟩ ∷= suc ⟨value⟩
         | zero
         | true
         | false

⟨type⟩ ∷= Nat | Bool
#+end_src
@@latex:\fi@@

Note that natural numbers are considered values only if
they are a chain of ~suc~'s applied to a (natural number) value.
- The “(natural number)” portion of that statement will be
  enforced by the typing rules.
- For instance, ~suc zero~ is a value
  (as is ~succ true~ according to the syntax,
  but the typing rules will forbid that.)
- ~succ~ also appears in a production for ~⟨term⟩~ to allow for its use in non-values
  (such as ~succ pred zero~, which should simplify to ~zero~ under our semantics.)

** Typing for natural numbers and booleans

#+begin_src text
                               
––––––––––––––––––– T-zero     
 Γ ⊢ zero : nat
 
#+end_src

#+begin_src text

   Γ ⊢ t : nat                   Γ ⊢ t : nat                 
–––––––––––––––––––– T-suc    –––––––––––––––––––– T-pred                                 
 Γ ⊢ suc t : nat               Γ ⊢ pred t : nat                                           

#+end_src
                         
#+begin_src text

––––––––––––––––––– T-true    –––––––––––––––––––– T-false
 Γ ⊢ true : bool               Γ ⊢ false : bool

#+end_src

#+begin_src text

    Γ ⊢ t : nat
–––––––––––––––––––––––– T-iszero
 Γ ⊢ iszero t : bool 

#+end_src

#+begin_src text

 Γ ⊢ b : bool    Γ ⊢ t₁ : A    Γ ⊢ t₂ : A
––––––––––––––––––––––––––––––––––––––––––––– T-if
         Γ ⊢ if b then t₁ else t₂ : A

#+end_src

** Semantics of natural numbers and booleans

#+begin_src text

      t ⟶ t′                              t ⟶ t′                 
–––––––––––––––––––– reduce-suc    –––––––––––––––––––– reduce-pred                                 
  suc t ⟶ suc t′                     pred t ⟶ pred t′                                           

#+end_src

#+begin_src text

      t ⟶ t′                                              
––––––––––––––––––––––––– reduce-iszero    ––––––––––––––––––––––– iszero-zero
  iszero t ⟶ iszero t′                       iszero zero ⟶ true                                           

#+end_src

The natural number predecessor of zero is zero.
And because of this, a successor can never be zero.
#+begin_src text

                                              
–––––––––––––––––––––– pred-zero    ––––––––––––––––––––––––––––– iszero-suc
  pred zero ⟶ zero                    iszero (suc t) ⟶ false                                           

#+end_src

#+begin_src text

 iszero t ⟶ false
–––––––––––––––––––– suc-pred    –––––––––––––––––––– pred-suc
 suc (pred t) ⟶ t                  pred (suc t) ⟶ t                                           

#+end_src

@@latex:\iffalse@@

** Semantics of natural numbers and booleans continued

@@latex:\fi@@

#+begin_src text

          tᵇ  ⟶  tᵇ′
–––––––––––––––––––––––––––––––––– reduce-if
 if tᵇ t₁ t₂  ⟶  if tᵇ′ t₁ t₂

#+end_src

#+begin_src text

––––––––––––––––––––––––– if-then
 if true t₁ t₂  ⟶  t₁

#+end_src

#+begin_src text

––––––––––––––––––––––––– if-else
 if false t₁ t₂  ⟶  t₂
#+end_src

* Products, records, sums and variants

** Preamble                                    :ignore:

We now add product and sum types to our language.
- And then later follow up with the slightly more sophisticated /record/
  and /variant/ types, which allow for named fields.

** Informal description of products and sums

A product
- is written using braces as ~{t,t}~, and
- we include /projection functions/ for accessing either element of a product,
  - written ~t.1~ and ~t.2~ respectively.

A sum
- is written as either
  - ~inl t as A~ (read “in the left type of ~A~”), or
  - ~inr t as A~ (read “in the right type of ~A~”), and
    - The reason for the ascription “~as A~” in the above will be discussed when
      we reach the typing rules.
- we include /case splitting/ to check whether the sum has the left or right type,
  - written ~case t of inl x₁ as A ⇒ t₁ | inr x₂ as A ⇒ t₂~.

** Syntax for products and sums

The syntax for products and sums are as described.
#+begin_src text
⟨term⟩ ∷= '{' ⟨term⟩ , ⟨term⟩ '}'
        | ⟨term⟩.1 | ⟨term⟩.2
        | inl ⟨term⟩ as ⟨type⟩ | inr ⟨term⟩ as ⟨type⟩
        | case ⟨term⟩ of inl var ⇒ ⟨term⟩ | inr var ⇒ ⟨term⟩
        
       
⟨value⟩ ∷= '{' ⟨value⟩ , ⟨value⟩ '}'
         | inl ⟨value⟩ as ⟨type⟩ | inr ⟨value⟩ as ⟨type⟩

⟨type⟩ ∷= ⟨type⟩ × ⟨type⟩
        | ⟨type⟩ + ⟨type⟩
#+end_src

Note that, as with ~suc~ for natural numbers, a product or sum
is only a value if its parts are themselves values.

** Typing for products

There's not much to note about the type rules for products.

#+begin_src text

 Γ ⊢ t₁ : A    Γ ⊢ t₂ : B                               
–––––––––––––––––––––––––––– T-pair
     Γ ⊢ {t₁ , t₂} : nat
 
#+end_src

#+begin_src text

 Γ ⊢ t : A × B               Γ ⊢ t : A × B          
–––––––––––––––– T-proj1    –––––––––––––––– T-proj2
  Γ ⊢ t.1 : A                 Γ ⊢ t.2 : B           
 
#+end_src

** Typing for sums

For sums, though, we can observe why it is that
we have put a type ascription on uses of ~inl~ and ~inr~.
- In our first typing rule, for ~inl~ we have no way to determine
  what the type ~B~ should be without the ascription.
- Similarly, in the rule for ~inr~, we have no way to determine the type ~A~.
- Given a term such as ~inl zero~, there are in fact infinite possible
  types; just fill in anything for ~B~ in ~Nat × B~.
  - But ~B~ might need to be a specific type because of the context
    that the term appears in.
- We /could/ construct a type system that uses the surrounding context
  of the term to determine the missing type automatically.
  - This is known as /type reconstruction/.
  - But we do not discuss this at the moment.
- An alternative approach is the use of /subtyping/.
  
#+begin_src text

           Γ ⊢ t : A
––––––––––––––––––––––––––––––––– T-inl
  Γ ⊢ (inl t as A + B) : A + B

#+end_src

#+begin_src text

           Γ ⊢ t : B
––––––––––––––––––––––––––––––––– T-inr
  Γ ⊢ (inr t as A + B) : A + B

#+end_src

#+begin_src text

 Γ ⊢ t₀ : A + B    Γ,(x₁ : A) ⊢ t₁ : C    Γ,(x₂ : B) ⊢ t₂ : C
––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––– T-case
  Γ ⊢ (case t of inl x₁ as A + B ⇒ t₁ | inr x₂ as A + B ⇒ t₁) : C

#+end_src

** Semantics of products

#+begin_src text

–––––––––––––––––––– value-proj1    –––––––––––––––––––– value-proj2
 {v₁ , v₂}.1 ⟶ v₁                    {v₁ , v₂}.1 ⟶ v₁

#+end_src

#+begin_src text

   t ⟶ t′                         t ⟶ t′
–––––––––––––– reduce-proj1    –––––––––––––– reduce-proj2
 t.1 ⟶ t′.1                     t.2 ⟶ t′.2

#+end_src

#+begin_src text

        t₁ ⟶ t₂′                                  t₂ ⟶ t₂′
––––––––––––––––––––––––– reduce-pair1    –––––––––––––––––––––––––– reduce-pair2
 {t₁ , t₂} ⟶ {t₁′ , t₂}                    {v₁ , t₂} ⟶ {v₁ , t₂′}

#+end_src

** Semantics of sums

#+begin_src text

–––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––– case-inl-value
 case (inl v) of inl x₁ as A ⇒ t₁ | inr x₂ as A ⇒ t₂   ⟶   t₁[x₁ ≔ v]

#+end_src

#+begin_src text

––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––– case-inl-value
 case (inr v) of inl x₁ as A ⇒ t₁ | inr x₂ as A ⇒ t₂   ⟶   t₂[x₂ ≔ v]

#+end_src

#+begin_src text

                          t ⟶ t′
–––––––––––––––––––––––––––––––––––––––––––––––––––––– case-reduce
     case t  of inl x₁ as A ⇒ t₁ | inr x₂ as A ⇒ t₂
 ⟶   case t′ of inl x₁ as A ⇒ t₁ | inr x₂ as A ⇒ t₂

#+end_src

#+begin_src text

          t ⟶ t′                                     t ⟶ t′
–––––––––––––––––––––––––––– reduce-inl    –––––––––––––––––––––––––––– reduce-inr
 inl t as A ⟶ inl t′ as A                   inr t as A ⟶ inr t′ as A

#+end_src

** Records and variants

:TODO:

* ~let~ bindings and recursion

** Preamble                                    :ignore:

Recall, from the untyped λ-calculus,
that recursive definitions could be expressed using this
“fixed-point” combinator, known as the Y-combinator.
#+begin_src text
fix = λ f → (λ x → f (λ y → x x y)) (λ x → f (λ y → x x y))
#+end_src
