# The swipl verion
ARG SWIPL_TAG=8.2.0

# Use the official swipl image as base
FROM swipl:${SWIPL_TAG}

# Set the name of the maintainers
MAINTAINER Habib Ghaffari Hadigheh, Mark Armstrong <ghaffh1@mcmaster.ca, armstmp@mcmaster.ca>

# Set the working directory
WORKDIR /opt/h2